Update erase flash version check logic
WildernessLabs/Meadow.CLI pull request #135
Opened 2022-03-12 18:29 UTC by adrianstevens

Fix for erase flash logic 

Compare to the mono version instead of the OS version since the OS version will reflect whatever has just been written to Meadow (i.e. we want the previous version not the current version)

2022-03-13 14:12 UTC, CartBlanche requested changes

2022-03-13 14:12 UTC, CartBlanche commented on Meadow.CLI/Commands/DeviceManagement/FlashOsCommand.cs
> +            if (previousOsVersion.CompareTo(new Version(MINIMUM_OS_VERSION)) < 0) {
@adrianstevens and the `MINIMUM_OS_VERSION` is still valid for `MonoVersion`? 
Is that kept in sync with `MeadowOsVersion`?

2022-03-13 23:07 UTC, adrianstevens commented on Meadow.CLI/Commands/DeviceManagement/FlashOsCommand.cs
> +            if (previousOsVersion.CompareTo(new Version(MINIMUM_OS_VERSION)) < 0) {
From Slack - the OS version and the runtime (mono) version are stored and retrieved separately but to date we've always released them together. Or said another way - the OS and mono versions should always match.





[11:30](https://wildernesslabs.slack.com/archives/CPWT8EZEK/p1647196213660139)
In the current CLI where we added the logic we're checking the OS version - but we're checking it after we've updated the OS so it will always get the version of the new OS, not the version we're replacing.
[11:32](https://wildernesslabs.slack.com/archives/CPWT8EZEK/p1647196351406069)
So it is possible that someone has mismatched mono and OS versions so checking the mono version isn't a perfect solution but it's highly unlikely that someone has a mono version installed that's greater than the OS and I can't think of any reasonable way to get into that stake.

2022-03-14 07:42 UTC, CartBlanche commented on Meadow.CLI/Commands/DeviceManagement/FlashOsCommand.cs
> +            if (previousOsVersion.CompareTo(new Version(MINIMUM_OS_VERSION)) < 0) {
Ok cool. I just wanted to make sure.

2022-03-14 07:43 UTC, merged