Send mpak crc and file size
WildernessLabs/Meadow.CLI pull request #260
Opened 2023-03-18 01:39 UTC by lamebrain

* Add Crc32 Hasher class
* Update package service to add mpak crc and file size

2023-03-18 07:44 UTC, CartBlanche requested changes

2023-03-18 07:44 UTC, CartBlanche commented on Meadow.CLI.Core/Common/Hasher.cs
Currently the Windows build is failing because this file hasn't been added to the Meadow.CLI.Core.VS2019.csproj. 
[Edit] See comment below about other CRC function/methods.

2023-03-18 07:44 UTC, CartBlanche commented on Meadow.CLI.Core/Common/Hasher.cs
> +    public async Task<string> CalculateCrc32(string filePath)
Not sure if you are aware, but we have some CRC related functions/methods in the  `Meadow.CLI.Core.DeviceManagement.Tools` namespace. If there isn't anything you can already use there, maybe move this into that namespace so all the CRC helper functions are centralised?

2023-03-18 20:40 UTC, lamebrain commented on Meadow.CLI.Core/Common/Hasher.cs
> +    public async Task<string> CalculateCrc32(string filePath)
Ah thanks, I was hoping something already existed and did a search, but came up empty. I'll find and use use the existing method as to avoid bringing in new dependencies.

2023-03-18 20:40 UTC, lamebrain commented on Meadow.CLI.Core/Common/Hasher.cs
Yeah, I saw that and was saddened. Will refactor to the existing method. Thanks!

2023-03-20 03:49 UTC, lamebrain commented
@CartBlanche alright, I ended up moving the new function into the existing namespace. VS2019 also fixed.

2023-03-20 13:49 UTC, CartBlanche approved these changes
LGTM

2023-03-20 13:51 UTC, merged