Mono to Runtime
WildernessLabs/Meadow.CLI pull request #364
Opened 2023-09-30 00:06 UTC by jorgedevs

2023-09-30 00:11 UTC, ctacke requested changes

2023-09-30 00:11 UTC, ctacke commented on Source/v2/Meadow.Hcom/Connections/SerialConnection.cs
> -    private const string RuntimeSucessfullyEnabledToken = "Meadow successfully started MONO";
These can't be changed.  These are messages HCOM on the device sends to us and we use for parsing.

2023-09-30 00:11 UTC, ctacke commented on Source/v2/Meadow.Hcom/DeviceInfo.cs
> -            deviceInfo.AppendLine($"    Mono: {RuntimeVersion}");
this change is valid

2023-10-04 15:55 UTC, CartBlanche approved these changes
LGTM

2023-10-04 15:56 UTC, merged